#!/usr/bin/python

import os
import optparse
from subprocess import Popen, PIPE, STDOUT

sqldir='/usr/local/DB-Class-Helper/sql'
dbname='~/dbclass.db'

#!/usr/bin/python

import os
import optparse
from subprocess import Popen, PIPE, STDOUT

dbname='~/dbclass.db'

usage = "usage: %prog [-f|-d|-r|-s] arg"
parser = optparse.OptionParser(usage)

parser.add_option("-f", "--file", dest="run_file",
                    action="store_true",
                    default=False,
                    help="Runs an sql file into the database")

parser.add_option("-d", "--dir", dest="run_all_files",
                    action="store_true",
                    default=False,
                    help="Runs all files in the given dir and checks answers against .answer files")

parser.add_option("-r", "--reset", dest="reset",
                    action="store_true",
                    default=False,
                    help="Resets the database")

parser.add_option("-s", "--sql", dest="run_sql",
                    action="store_true",
                    default=False,
                    help="Runs sql on the database")


options,args = parser.parse_args()

if len(args)==0 and not options.reset:
	parser.error(usage)

if options.run_file:
	file=args[0]
	cmd="sqlite3 -header %s <%s" % (dbname,file)
	os.system(cmd)

elif options.run_all_files:
	dir=args[0]
    	for f in (os.listdir(dir)):
	
			
		fb,ext=os.path.splitext(f)
		ff=os.path.join(dir, f)
		fout=os.path.join(dir, fb+'.out')
		fans=os.path.join(dir, fb+'.answer')

		if ext=='.sql':
			cmd='sqlite3 -header %s <"%s" >"%s"' % (dbname,ff,fout)
			print cmd
			p = Popen(cmd, shell=True, stdin=PIPE, stdout=PIPE, stderr=STDOUT, close_fds=True)
			output = p.stdout.read()
			
			if output<>'':
				print "-%-s:incorrect" % f
				print "...sql error in %s" % f
				print "..."+output
				print
			else:

				cmd='diff -q "%s" "%s"' % (fout,fans)
				p = Popen(cmd, shell=True, stdin=PIPE, stdout=PIPE, stderr=STDOUT, close_fds=True)
				output = p.stdout.read()

				if output:
					print "-%s-:*incorrect*" % f
					cmd='diff -y "%s" "%s"' % (fout,fans)
					p = Popen(cmd, shell=True, stdin=PIPE, stdout=PIPE, stderr=STDOUT, close_fds=True)
					output = p.stdout.read()
					print "--------"
					print output
					print "--------"
					print
				else:
					print "-%s-:correct" % f
					print

			
elif options.run_sql:
	sql=args[0]
	cmd="sqlite3 -header %s '%s'" % (dbname,sql)
	os.system(cmd)

elif options.reset:
	cmd="rm %s" % (dbname)

	for f in os.listdir(sqldir):
		print 'Importing %s' % f
		cmd="sqlite3 -header %s < '%s/%s'" % (dbname,sqldir,f)
		print cmd
		p = Popen(cmd, shell=True, stdin=PIPE, stdout=PIPE, stderr=STDOUT, close_fds=True)
		output = p.stdout.read()

else:
	parser.error(usage)
